# Generated by Django 3.0.8 on 2020-07-14 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='media/images/bg')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('background_color', models.CharField(blank=True, default='#FFFFFF', max_length=15, null=True)),
                ('rounded', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/images/bg')),
                ('item_size', models.IntegerField()),
                ('font', models.CharField(default='Helvetica', max_length=30)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('pixel', models.CharField(blank=True, max_length=50, null=True)),
                ('analytics', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('link', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='media/images/items')),
                ('reference', models.SlugField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
            options={
                'unique_together': {('reference', 'store')},
            },
        ),
    ]
