# Generated by Django 3.0.8 on 2020-07-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200715_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_size',
            field=models.IntegerField(default=12),
        ),
    ]
