# Generated by Django 3.0.8 on 2020-07-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200715_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rounded',
            field=models.IntegerField(default=0),
        ),
    ]
