# Generated by Django 3.0.8 on 2020-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200716_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/items/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/bg/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/logos/'),
        ),
    ]
