# Generated by Django 3.0.8 on 2020-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200716_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
