# Generated by Django 3.0.8 on 2020-07-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20200716_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_description', models.CharField(default='Helvetica', max_length=30)),
                ('font_title', models.CharField(default='Helvetica', max_length=30)),
                ('title_color', models.CharField(default='#000', max_length=15)),
                ('description_color', models.CharField(default='#000', max_length=15)),
                ('background_color', models.CharField(default='transparent', max_length=15)),
                ('rounded', models.IntegerField(default=0)),
                ('item_size', models.IntegerField(default=12)),
                ('image_position', models.CharField(default='top', max_length=15)),
                ('padding', models.IntegerField(default=15)),
                ('border_color', models.CharField(default='#FFFFFF', max_length=15)),
                ('border_size', models.IntegerField(default=1)),
                ('border_style', models.CharField(default='solid', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_description', models.CharField(default='Helvetica', max_length=30)),
                ('font_title', models.CharField(default='Helvetica', max_length=30)),
                ('title_color', models.CharField(default='#000', max_length=15)),
                ('description_color', models.CharField(default='#000', max_length=15)),
                ('background_color', models.CharField(default='transparent', max_length=15)),
                ('background_header', models.CharField(default='transparent', max_length=15)),
                ('logo_position', models.CharField(default='right', max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='background_header',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='font_description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='font_title',
        ),
        migrations.RemoveField(
            model_name='store',
            name='item_size',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rounded',
        ),
        migrations.RemoveField(
            model_name='store',
            name='title_color',
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='core.ItemTheme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='core.StoreTheme')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='core.ItemTheme'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='core.Theme'),
        ),
    ]
