# Generated by Django 3.0.8 on 2020-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200716_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='background_image',
        ),
        migrations.AddField(
            model_name='storetheme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/bg/'),
        ),
    ]
