# Generated by Django 3.0.8 on 2020-07-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200722_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='items',
        ),
        migrations.AddField(
            model_name='itemtheme',
            name='theme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='core.Theme'),
        ),
    ]
