# Generated by Django 3.0.8 on 2020-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200722_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='size',
            field=models.IntegerField(default=12),
        ),
    ]
